spring.application.name=application-service

#eureka.client.service-url.defaultZone=http://localhost:8761/eureka
#
#server.port=8083
#
#spring.datasource.url=jdbc:postgresql://localhost:5432/application_db
#spring.datasource.username=postgres
#spring.datasource.password=lilly@2808
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true

#management.tracing.sampling.probability=1.0
#management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans

spring.config.import=optional:configserver:http://localhost:8888